[tool.poetry]
name = "mchat"
version = "0.1.0"
description = "ChatGPT TUI Application"
authors = ["jspv <jspvgithub@twinleaf.xyz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
requests = "^2.28.1"
openai = "^1.3.5"
pyyaml = "^6.0"
tiktoken = "^0.4.0"
textual = "^0.44.0"
rich = "^13.5.1"
dynaconf = "^3.2.2"
pyperclip = "^1.8.2"
urllib3 = "^2.1.0"
apsw = "^3.44.0.0"
retry = "^0.9.2"
langchain = "^0.0.341"
pytz = "^2023.3.post1"

[tool.poetry.scripts]
mchat = "mchat.mchat:main"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
textual-dev = "^1.2.1"
jupyter = "^1.0.0"
black = "^23.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

