[tool.poetry]
name = "mchat"
version = "0.1.0"
description = "ChatGPT TUI Application"
authors = ["jspv <jspvgithub@twinleaf.xyz>"]
readme = "README.md"

[tool.poetry.dependencies]
#python = "^3.10"
python = ">=3.10,<3.12"
requests = "^2.28.1"
openai = "^0.27.8"
ask-sdk = "^1.19.0"
botocore = "^1.30.0"
pyyaml = "^6.0"
langchain = {extras = ["llm"], version = "^0.0.232"}
tiktoken = "^0.4.0"
textual = "^0.29.0"
rich = "^13.5.1"
dynaconf = "^3.2.2"

[tool.poetry.scripts]
mchat = "mchat.mchat:main"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
jupyter = "^1.0.0"
textual-dev = "^1.0.1"
httpx = "^0.24.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
