[tool.poetry]
name = "mchat"
version = "0.1.0"
description = "ChatGPT TUI Application"
authors = ["jspv <jspvgithub@twinleaf.xyz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
requests = "^2.28.1"
openai = "^0.27.8"
pyyaml = "^6.0"
langchain = "^0.0.339"
tiktoken = "^0.4.0"
textual = "^0.41.0"
rich = "^13.5.1"
dynaconf = "^3.2.2"
pyperclip = "^1.8.2"
urllib3 = "^2.1.0"

[tool.poetry.scripts]
mchat = "mchat.mchat:main"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
textual-dev = "^1.2.1"
httpx = "^0.24.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
