# Models
# sections need to start with model. (with period) and no other periods in the section name
[models.chat.gpt-35-turbo]
api_key = "@format {this.openai_api_key}"
model = "gpt-3.5-turbo"
api_type = "open_ai"
base_url = "https://api.openai.com/v1"
_max_context = 16385
_max_tokens = 4096
_cost_input = 0.0010
_cost_output = 0.0020

[models.chat.gpt-4-turbo]
api_key = "@format {this.openai_api_key}"
model = "gpt-4-1106-preview"
api_type = "open_ai"
base_url = "https://api.openai.com/v1"
_max_tokens = 4096
_max_context = 128000
_cost_input = 0.01
_cost_output = 0.03

[models.chat.gpt-4o]
api_key = "@format {this.openai_api_key}"
model = "gpt-4o"
api_type = "open_ai"
base_url = "https://api.openai.com/v1"
_max_tokens = 40000
_max_context = 128000
_cost_input = 0.005
_cost_output = 0.0015

[models.chat.azure_openai_gpt_35]
api_key = "@format {this.azure_openai_api_key}"
api_type = "azure"
model = "gpt-3.5-turbo"
azure_deployment = "gpt-35-turbo"
azure_endpoint = "@format {this.azure_openai_base_url}"
api_version = "2023-09-01-preview"
# base_url = "@format {this.azure_openai_base_url}"
_max_tokens = 4096
_max_context = 16385
_cost_input = 0.0015
_cost_output = 0.002

[models.chat.azure_openai_gpt_4]
api_key = "@format {this.azure_openai_api_key}"
api_type = "azure"
model = "gpt-4"
azure_deployment = "gpt-4"
azure_endpoint = "@format {this.azure_openai_base_url}"
api_version = "2023-09-01-preview"
# base_url = "@format {this.azure_openai_base_url}"
_max_tokens = 4096
_max_context = 16385
_cost_input = 0.01
_cost_output = 0.03

[models.image.dall-e-2]
api_key = "@format {this.openai_api_key}"
model = "dall-e-2"
api_type = "open_ai"
size = "1024x1024"
quality = "standard"
num_images = 1
_cost_output = 0.020

[models.image.dall-e-3]
api_key = "@format {this.openai_api_key}"
model = "dall-e-3"
api_type = "open_ai"
size = "1024x1024"
quality = "standard"
_cost_output = 0.080

[models.embedding.text-embedding-ada-002]
api_key = "@format {this.openai_api_key}"
model = "text-embedding-ada-002"
api_type = "open_ai"
_cost_input = 0.0001

[models.embedding.azure_text-embedding-ada-002]
api_key = "@format {this.azure_openai_api_key}"
model = "text-embedding-ada-002"
api_type = "azure"
api_version = "2023-09-01-preview"
base_url = "@format {this.azure_openai_base_url}"
_cost_input = 0.0001

[defaults]

# chat_model = "gpt-35-turbo"
# chat_model = "azure_openai_gpt_4"
chat_model = "gpt-4o"
chat_temperature = 0.7
persona = "default"

image_model = "dall-e-3"

embedding_model = "text-embedding-ada-002"

# Using ConversationSummaryBufferMemory - specify model and max_tokens
# memory_model = "gpt-35-turbo"
memory_model = "gpt-4o"
# memory_model = "azure_openai_gpt_35"
memory_model_temperature = 0.1
memory_model_max_tokens = 2048

# in .secrets.toml
# openai_api_key = "oai_ai_api_key_goes_here"
# azure_openai_api_key = "ms_openai_api_key_goes_here"
# azure_openai_base_url = "your deployment base url goes here"
